import { useState, useEffect, useCallback, useRef, memo } from 'react';
import { AlertCircle, RefreshCw, Loader2, Clock, Copy, Check } from 'lucide-react';
import { api } from '../api';
import { useLanguage } from '../context/LanguageContext';

type SubtitleCue = {
  start: number;
  duration: number;
  text: string;
};

type LanguageInfo = {
  code: string;
  name: string;
  isAutoGenerated: boolean;
};

type CaptionsPanelProps = {
  videoId: string;
  currentPlaybackTime: number;
  onSync?: () => void;
  onSeek?: (seconds: number) => void;
};

function formatTime(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${s.toString().padStart(2, '0')}`;
}

const CACHE = new Map<string, { languages: LanguageInfo[]; subtitles: SubtitleCue[] }>();
const ACTIVE_REQUESTS = new Map<string, AbortController>();

function findActiveCue(subtitles: SubtitleCue[], time: number): SubtitleCue | undefined {
  return subtitles.find((cue, index, arr) => {
    const next = arr[index + 1]?.start;
    const end = cue.duration > 0 ? cue.start + cue.duration : (next ?? cue.start + 4);
    return time >= cue.start && time < end;
  });
}

const DEFAULT_LANG = 'en';

function CaptionsPanel({ videoId, currentPlaybackTime, onSync, onSeek }: CaptionsPanelProps) {
  const { t } = useLanguage();
  const [languages, setLanguages] = useState<LanguageInfo[]>([]);
  const [subtitles, setSubtitles] = useState<SubtitleCue[]>([]);
  const [loadedLang, setLoadedLang] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const listRef = useRef<HTMLDivElement>(null);
  const activeRef = useRef<HTMLButtonElement>(null);

  const activeCue = findActiveCue(subtitles, currentPlaybackTime);
  const activeIndex = activeCue ? subtitles.indexOf(activeCue) : -1;

  useEffect(() => {
    if (activeRef.current && listRef.current) {
      const container = listRef.current;
      const el = activeRef.current;
      const containerRect = container.getBoundingClientRect();
      const elRect = el.getBoundingClientRect();
      if (elRect.top < containerRect.top || elRect.bottom > containerRect.bottom) {
        el.scrollIntoView({ behavior: 'smooth', block: 'center' });
      }
    }
  }, [activeIndex]);

  useEffect(() => {
    setLanguages([]);
    setSubtitles([]);
    setLoadedLang('');
    setIsLoading(true);
    setError(null);

    CACHE.clear();
    ACTIVE_REQUESTS.forEach(c => c.abort());
    ACTIVE_REQUESTS.clear();
  }, [videoId]);

  const getOrFetch = useCallback(async (langCode: string): Promise<{ languages: LanguageInfo[]; subtitles: SubtitleCue[] } | null> => {
    const key = `${videoId}_${langCode}`;
    if (ACTIVE_REQUESTS.has(key)) return null;

    const cached = CACHE.get(key);
    if (cached) return cached;

    const controller = new AbortController();
    ACTIVE_REQUESTS.set(key, controller);

    try {
      const res = await api.get<{
        success: boolean;
        data?: {
          languages: LanguageInfo[];
          subtitles: SubtitleCue[];
          selectedLanguage: string;
        };
        error?: string;
      }>(`/subtitles/${videoId}`, { params: { lang: langCode }, signal: controller.signal });

      if (!res.data?.success || !res.data?.data) {
        throw new Error(res.data?.error || 'No captions available');
      }

      const { languages: langs, subtitles: subs } = res.data.data;
      const sorted = [...subs].sort((a, b) => a.start - b.start);
      const data = { languages: langs, subtitles: sorted };
      CACHE.set(key, data);
      return data;
    } catch (err: any) {
      if (err?.name === 'CanceledError' || err?.code === 'ERR_CANCELED') return null;
      throw err;
    } finally {
      ACTIVE_REQUESTS.delete(key);
    }
  }, [videoId]);

  const load = useCallback(async (langCode: string) => {
    setIsLoading(true);
    setError(null);
    setSubtitles([]);
    try {
      const data = await getOrFetch(langCode);
      if (data) {
        setLanguages(data.languages);
        setSubtitles(data.subtitles);
        setLoadedLang(langCode);
      } else {
        setLoadedLang(langCode);
      }
    } catch (err: any) {
      const msg = err?.response?.data?.error || err?.message || 'Failed to load captions';
      setError(msg);
    } finally {
      setIsLoading(false);
    }
  }, [getOrFetch]);

  useEffect(() => {
    load(DEFAULT_LANG);
  }, [load]);

  const handleRetry = () => {
    CACHE.delete(`${videoId}_${loadedLang || DEFAULT_LANG}`);
    load(loadedLang || DEFAULT_LANG);
  };

  const handleCopyTranscript = async () => {
    if (!activeCue) return;
    try {
      await navigator.clipboard.writeText(activeCue.text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy transcript:', err);
    }
  };

  const selectedLangInfo = languages.find(l => l.code === loadedLang);

  return (
    <div className="rounded-xl border border-gray-200/60 bg-white dark:border-white/10 dark:bg-dark-navy">
      <div className="flex items-center justify-between border-b border-gray-200/60 px-4 py-3 dark:border-white/10">
        <h2 className="text-sm font-bold text-gray-900 dark:text-white">{t('videoPage.subtitles')}</h2>
        <div className="flex items-center gap-2">
          {onSync && !isLoading && !error && subtitles.length > 0 && (
            <button
              onClick={onSync}
              className="inline-flex items-center gap-1 rounded-lg px-2.5 py-1.5 text-xs font-semibold text-gray-600 transition-colors hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-white/10"
              title={t('videoPage.syncSubtitle')}
            >
              <Clock className="h-3.5 w-3.5" />
              {t('videoPage.syncSubtitle')}
            </button>
          )}
          {!isLoading && !error && activeCue && (
            <button
              onClick={handleCopyTranscript}
              className="inline-flex items-center justify-center w-7 h-7 rounded-lg text-gray-500 transition-colors hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-white/10"
              aria-label="Copy transcript"
            >
              {copied ? <Check className="h-3.5 w-3.5 text-green-500" /> : <Copy className="h-3.5 w-3.5" />}
            </button>
          )}
          {selectedLangInfo?.isAutoGenerated && (
            <span className="rounded-md bg-amber-100 px-2 py-0.5 text-[11px] font-medium text-amber-700 dark:bg-amber-900/30 dark:text-amber-400">
              {t('videoPage.autoGenerated')}
            </span>
          )}
        </div>
      </div>

      <div className="p-4">
        {isLoading ? (
          <div className="flex flex-col items-center justify-center gap-3 py-8 text-gray-500 dark:text-gray-400">
            <Loader2 className="h-6 w-6 animate-spin" />
            <p className="text-sm">{t('videoPage.loadingCaptions')}</p>
          </div>
        ) : error ? (
          <div className="flex flex-col items-center justify-center gap-3 py-8">
            <AlertCircle className="h-6 w-6 text-red-500" />
            <p className="text-sm text-gray-600 dark:text-gray-300">{error}</p>
            <button
              onClick={handleRetry}
              className="inline-flex items-center gap-1.5 rounded-lg bg-brand-coral px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-brand-pink"
            >
              <RefreshCw className="h-4 w-4" />
              {t('videoPage.tryAgain')}
            </button>
          </div>
        ) : subtitles.length === 0 ? (
          <div className="min-h-[3rem]" />
        ) : (
          <div ref={listRef} className="max-h-[400px] overflow-y-auto space-y-1">
            {subtitles.map((cue, i) => {
              const isActive = i === activeIndex;
              return (
                <button
                  key={i}
                  ref={isActive ? activeRef : undefined}
                  onClick={() => onSeek?.(cue.start)}
                  className={`w-full text-left flex items-start gap-3 rounded-lg p-3 transition-colors ${
                    isActive
                      ? 'bg-brand-coral/10 dark:bg-brand-coral/20 border border-brand-coral/30'
                      : 'hover:bg-gray-50 dark:hover:bg-white/5 border border-transparent'
                  }`}
                >
                  <span className="shrink-0 mt-0.5 min-w-[4rem] text-xs font-mono text-gray-400 dark:text-gray-500">
                    {formatTime(cue.start)}
                  </span>
                  <span className={`text-sm leading-relaxed ${
                    isActive
                      ? 'font-medium text-gray-900 dark:text-white'
                      : 'text-gray-600 dark:text-gray-300'
                  }`}>
                    {cue.text}
                  </span>
                </button>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}

export default memo(CaptionsPanel);
