import { useState, useEffect, useCallback, useRef } from 'react';

type SubtitleCue = {
  start: number;
  duration: number;
  text: string;
};

type VideoLearningData = {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  subtitles: SubtitleCue[];
};

interface YouTubeSubtitlesHook {
  learningData: VideoLearningData | null;
  isLoading: boolean;
  error: string | null;
  extractSubtitlesFromPlayer: () => Promise<void>;
  reset: () => void;
}

const SUBTITLES_CACHE = new Map<string, VideoLearningData>();
const ACTIVE_REQUESTS = new Map<string, AbortController>();
const LAST_REQUEST_TIME = new Map<string, number>();
const MIN_REQUEST_INTERVAL = 5000;

function parseXMLSubtitleResponse(xmlText: string): SubtitleCue[] {
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(xmlText, 'text/xml');
  const textElements = xmlDoc.getElementsByTagName('text');
  const cues: SubtitleCue[] = [];

  for (let i = 0; i < textElements.length; i++) {
    const textElement = textElements[i];
    const startAttr = textElement.getAttribute('start');
    const durAttr = textElement.getAttribute('dur');
    const text = textElement.textContent || '';

    if (startAttr && durAttr && text.trim()) {
      const start = parseFloat(startAttr);
      const duration = parseFloat(durAttr);
      cues.push({ start, duration, text: text.trim() });
    }
  }

  return cues;
}

function formatLanguageName(code: string): string {
  const languageNames: Record<string, string> = {
    'en': 'English',
    'es': 'Spanish',
    'fr': 'French',
    'de': 'German',
    'it': 'Italian',
    'pt': 'Portuguese',
    'ru': 'Russian',
    'ja': 'Japanese',
    'ko': 'Korean',
    'zh': 'Chinese',
    'hi': 'Hindi',
    'ar': 'Arabic',
    'th': 'Thai',
    'vi': 'Vietnamese',
    'tr': 'Turkish',
    'pl': 'Polish',
    'nl': 'Dutch',
    'sv': 'Swedish',
    'da': 'Danish',
    'no': 'Norwegian',
    'fi': 'Finnish',
    'cs': 'Czech',
    'hu': 'Hungarian',
    'ro': 'Romanian',
    'bg': 'Bulgarian',
    'hr': 'Croatian',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'et': 'Estonian',
    'lv': 'Latvian',
    'lt': 'Lithuanian',
    'uk': 'Ukrainian',
    'he': 'Hebrew',
    'el': 'Greek',
  };

  return languageNames[code] || code.toUpperCase();
}

export function useYouTubeSubtitles(videoId?: string): YouTubeSubtitlesHook {
  const [learningData, setLearningData] = useState<VideoLearningData | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const extractionAttemptedRef = useRef(false);
  const previousVideoIdRef = useRef<string | undefined>(undefined);

  const extractSubtitlesFromPlayer = useCallback(async () => {
    if (!videoId) return;

    const now = Date.now();
    const lastRequestTime = LAST_REQUEST_TIME.get(videoId);
    if (lastRequestTime && now - lastRequestTime < MIN_REQUEST_INTERVAL) {
      return;
    }

    if (ACTIVE_REQUESTS.has(videoId)) {
      return;
    }

    if (SUBTITLES_CACHE.has(videoId)) {
      const cachedData = SUBTITLES_CACHE.get(videoId);
      if (cachedData) {
        setLearningData(cachedData);
        setIsLoading(false);
        setError(null);
        return;
      }
    }

    setIsLoading(true);
    setError(null);

    const controller = new AbortController();
    ACTIVE_REQUESTS.set(videoId, controller);
    LAST_REQUEST_TIME.set(videoId, now);

    try {
      const listUrl = `https://video.google.com/timedtext?type=list&v=${videoId}&asrs=1`;
      const listResponse = await fetch(listUrl, { signal: controller.signal });

      if (!listResponse.ok) {
        throw new Error(`Failed to fetch subtitle list: ${listResponse.status}`);
      }

      const listText = await listResponse.text();
      const parser = new DOMParser();
      const xmlDoc = parser.parseFromString(listText, 'text/xml');

      const langElements = xmlDoc.getElementsByTagName('lang');
      const languages = Array.from(langElements).map(el => el.textContent || '');

      if (languages.length === 0) {
        setError('No subtitles available');
        setIsLoading(false);
        return;
      }

      const defaultLang = 'en';
      const selectedLang = languages.includes(defaultLang) ? defaultLang : languages[0];

      const subtitlesUrl = `https://video.google.com/timedtext?lang=${selectedLang}&v=${videoId}`;
      const subtitlesResponse = await fetch(subtitlesUrl, { signal: controller.signal });

      if (!subtitlesResponse.ok) {
        throw new Error(`Failed to fetch subtitles: ${subtitlesResponse.status}`);
      }

      const subtitlesText = await subtitlesResponse.text();
      const subtitleCues = parseXMLSubtitleResponse(subtitlesText);

      if (subtitleCues.length === 0) {
        setError('No subtitle content available');
        setIsLoading(false);
        return;
      }

      const sortedCues = subtitleCues.sort((a, b) => a.start - b.start);
      const isAutoGenerated = selectedLang === 'en' && !languages.includes('en');

      const result: VideoLearningData = {
        languageCode: selectedLang,
        languageName: formatLanguageName(selectedLang),
        isAutoGenerated,
        subtitles: sortedCues,
      };

      SUBTITLES_CACHE.set(videoId, result);
      setLearningData(result);
      setIsLoading(false);
      setError(null);

    } catch (err) {
      if (err instanceof Error && err.name === 'AbortError') {
        return;
      }
      console.error('[useYouTubeSubtitles] Error fetching subtitles:', err);
      setError(err instanceof Error ? err.message : 'Failed to fetch subtitles');
      setIsLoading(false);
    } finally {
      ACTIVE_REQUESTS.delete(videoId);
    }
  }, [videoId]);

  const reset = useCallback(() => {
    if (previousVideoIdRef.current && previousVideoIdRef.current !== videoId) {
      SUBTITLES_CACHE.delete(previousVideoIdRef.current);
      ACTIVE_REQUESTS.delete(previousVideoIdRef.current);
      LAST_REQUEST_TIME.delete(previousVideoIdRef.current);
    }
    previousVideoIdRef.current = videoId;

    setLearningData(null);
    setError(null);
    setIsLoading(false);
    extractionAttemptedRef.current = false;
  }, [videoId]);

  useEffect(() => {
    reset();
  }, [videoId, reset]);

  return {
    learningData,
    isLoading,
    error,
    extractSubtitlesFromPlayer,
    reset,
  };
}
