export interface SubtitleCue {
  start: number;
  duration: number;
  text: string;
}

export interface VideoLearningData {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  subtitles: SubtitleCue[];
}

interface CaptionTrack {
  baseUrl?: string;
  languageCode?: string;
  name?: {
    simpleText?: string;
    runs?: Array<{ text?: string }>;
  };
  kind?: string;
}

interface TimedTextTrack {
  languageCode: string;
  languageName: string;
  kind?: string;
}

const FETCH_TIMEOUT = 10000;
const CACHE_TTL = 15 * 60 * 1000;
const learningCache = new Map<string, { data: VideoLearningData; timestamp: number }>();

function decodeHtml(value: string): string {
  return value
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#(\d+);/g, (_match, code) => String.fromCharCode(Number(code)));
}

function normalizeText(value: string): string {
  return decodeHtml(value).replace(/\s+/g, ' ').trim();
}

function getTrackName(track: CaptionTrack): string {
  if (track.name?.simpleText) return track.name.simpleText;
  return track.name?.runs?.map((run) => run.text || '').join('') || track.languageCode || 'Original language';
}

async function fetchText(url: string, accept = '*/*'): Promise<string> {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), FETCH_TIMEOUT);

  try {
    const response = await fetch(url, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (compatible; Wasla/1.0)',
        Accept: accept,
      },
      signal: controller.signal,
    });

    if (!response.ok) {
      throw new Error(`Request failed: ${response.status} ${response.statusText}`);
    }

    return await response.text();
  } finally {
    clearTimeout(timeoutId);
  }
}

async function postJson(url: string, body: unknown): Promise<unknown> {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), FETCH_TIMEOUT);

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'User-Agent': 'Mozilla/5.0 (compatible; Wasla/1.0)',
        Accept: 'application/json,*/*',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(body),
      signal: controller.signal,
    });

    if (!response.ok) {
      throw new Error(`Request failed: ${response.status} ${response.statusText}`);
    }

    return await response.json();
  } finally {
    clearTimeout(timeoutId);
  }
}

function extractJsonAfterMarker(html: string, marker: string): unknown | null {
  const markerIndex = html.indexOf(marker);
  if (markerIndex === -1) return null;

  const start = html.indexOf('{', markerIndex + marker.length);
  if (start === -1) return null;

  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let i = start; i < html.length; i += 1) {
    const char = html[i];

    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (char === '\\') {
        escaped = true;
      } else if (char === '"') {
        inString = false;
      }
      continue;
    }

    if (char === '"') {
      inString = true;
    } else if (char === '{') {
      depth += 1;
    } else if (char === '}') {
      depth -= 1;
      if (depth === 0) {
        try {
          return JSON.parse(html.slice(start, i + 1));
        } catch {
          return null;
        }
      }
    }
  }

  return null;
}

function getCaptionTracks(playerResponse: unknown): CaptionTrack[] {
  const response = playerResponse as {
    captions?: {
      playerCaptionsTracklistRenderer?: {
        captionTracks?: CaptionTrack[];
      };
    };
  };

  return response.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
}

function extractInnertubeConfig(html: string): { apiKey: string; clientVersion: string } | null {
  const apiKey = html.match(/"INNERTUBE_API_KEY":"([^"]+)"/)?.[1];
  const clientVersion = html.match(/"INNERTUBE_CONTEXT_CLIENT_VERSION":"([^"]+)"/)?.[1];
  if (!apiKey || !clientVersion) return null;
  return { apiKey, clientVersion };
}

async function fetchPlayerResponseFallback(videoId: string, html: string): Promise<unknown | null> {
  const config = extractInnertubeConfig(html);
  if (!config) return null;

  return postJson(`https://www.youtube.com/youtubei/v1/player?key=${config.apiKey}`, {
    context: {
      client: {
        clientName: 'WEB',
        clientVersion: config.clientVersion,
      },
    },
    videoId,
  });
}

function chooseOriginalTrack(tracks: CaptionTrack[]): CaptionTrack | undefined {
  if (tracks.length === 0) return undefined;
  return tracks.find((track) => track.kind !== 'asr') || tracks[0];
}

function parseTimedTextTrackList(payload: string): TimedTextTrack[] {
  const matches = payload.matchAll(/<track\s+([^>]+)>/g);
  return Array.from(matches)
    .map((match) => {
      const attrs = match[1] || '';
      const languageCode = attrs.match(/lang_code="([^"]+)"/)?.[1] || '';
      const languageName = attrs.match(/lang_original="([^"]+)"/)?.[1]
        || attrs.match(/name="([^"]+)"/)?.[1]
        || languageCode;
      const kind = attrs.match(/kind="([^"]+)"/)?.[1];
      return {
        languageCode,
        languageName: decodeHtml(languageName),
        kind,
      };
    })
    .filter((track) => track.languageCode);
}

async function fetchTimedTextTrack(videoId: string): Promise<{ track: TimedTextTrack; subtitles: SubtitleCue[] } | null> {
  const listPayload = await fetchText(`https://video.google.com/timedtext?type=list&v=${encodeURIComponent(videoId)}`, 'application/xml,text/xml,*/*');
  const tracks = parseTimedTextTrackList(listPayload);
  const track = tracks.find((item) => item.kind !== 'asr') || tracks[0];
  if (!track) return null;

  const params = new URLSearchParams({
    v: videoId,
    lang: track.languageCode,
    fmt: 'json3',
  });
  if (track.kind) params.set('kind', track.kind);

  try {
    const jsonPayload = await fetchText(`https://video.google.com/timedtext?${params.toString()}`, 'application/json,text/plain,*/*');
    const subtitles = parseJson3Subtitles(jsonPayload);
    if (subtitles.length > 0) return { track, subtitles };
  } catch {
    // Fall back to XML timedtext below.
  }

  params.delete('fmt');
  const xmlPayload = await fetchText(`https://video.google.com/timedtext?${params.toString()}`, 'application/xml,text/xml,*/*');
  const subtitles = parseXmlSubtitles(xmlPayload);
  if (subtitles.length === 0) return null;
  return { track, subtitles };
}

function parseJson3Subtitles(payload: string): SubtitleCue[] {
  const parsed = JSON.parse(payload) as {
    events?: Array<{
      tStartMs?: number;
      dDurationMs?: number;
      segs?: Array<{ utf8?: string }>;
    }>;
  };

  return (parsed.events || [])
    .map((event) => {
      const text = (event.segs || [])
        .map((seg) => seg.utf8 || '')
        .join('')
        .replace(/\n/g, ' ');

      return {
        start: (event.tStartMs || 0) / 1000,
        duration: (event.dDurationMs || 0) / 1000,
        text: normalizeText(text),
      };
    })
    .filter((cue) => cue.text.length > 0);
}

function parseXmlSubtitles(payload: string): SubtitleCue[] {
  const matches = payload.matchAll(/<text[^>]*start="([^"]+)"[^>]*(?:dur="([^"]+)")?[^>]*>([\s\S]*?)<\/text>/g);
  return Array.from(matches)
    .map((match) => ({
      start: Number(match[1]) || 0,
      duration: Number(match[2]) || 0,
      text: normalizeText(match[3] || ''),
    }))
    .filter((cue) => cue.text.length > 0);
}

async function fetchSubtitlesFromTrack(track: CaptionTrack): Promise<SubtitleCue[]> {
  if (!track.baseUrl) return [];

  const separator = track.baseUrl.includes('?') ? '&' : '?';
  const jsonUrl = `${track.baseUrl}${separator}fmt=json3`;

  try {
    const payload = await fetchText(jsonUrl, 'application/json,text/plain,*/*');
    const cues = parseJson3Subtitles(payload);
    if (cues.length > 0) return cues;
  } catch {
    // Fall back to the default XML timedtext response below.
  }

  const xmlPayload = await fetchText(track.baseUrl, 'application/xml,text/xml,*/*');
  return parseXmlSubtitles(xmlPayload);
}

export async function fetchVideoLearningData(videoId: string): Promise<VideoLearningData | null> {
  const cached = learningCache.get(videoId);
  if (cached && Date.now() - cached.timestamp < CACHE_TTL) {
    return cached.data;
  }

  const watchHtml = await fetchText(`https://www.youtube.com/watch?v=${videoId}`, 'text/html,application/xhtml+xml,*/*');
  const playerResponse = extractJsonAfterMarker(watchHtml, 'ytInitialPlayerResponse');
  let tracks = getCaptionTracks(playerResponse);

  if (tracks.length === 0) {
    const fallbackPlayerResponse = await fetchPlayerResponseFallback(videoId, watchHtml);
    tracks = getCaptionTracks(fallbackPlayerResponse);
  }

  const track = chooseOriginalTrack(tracks);
  let timedTextFallback: { track: TimedTextTrack; subtitles: SubtitleCue[] } | null = null;
  let subtitles: SubtitleCue[] = [];
  let subtitlesSource: 'captionTrack' | 'timedText' | null = null;

  if (track) {
    subtitles = await fetchSubtitlesFromTrack(track);
    if (subtitles.length > 0) subtitlesSource = 'captionTrack';
  }

  if (subtitles.length === 0) {
    try {
      timedTextFallback = await fetchTimedTextTrack(videoId);
      subtitles = timedTextFallback?.subtitles || [];
      if (subtitles.length > 0) subtitlesSource = 'timedText';
    } catch {
      subtitles = [];
    }
  }

  if (subtitles.length === 0) return null;

  const languageCode = subtitlesSource === 'captionTrack'
    ? track?.languageCode || 'auto'
    : timedTextFallback?.track.languageCode || 'auto';
  const data: VideoLearningData = {
    languageCode,
    languageName: subtitlesSource === 'captionTrack'
      ? track ? getTrackName(track) : 'Original language'
      : timedTextFallback?.track.languageName || 'Original language',
    isAutoGenerated: subtitlesSource === 'captionTrack'
      ? track?.kind === 'asr'
      : timedTextFallback?.track.kind === 'asr',
    subtitles,
  };

  learningCache.set(videoId, { data, timestamp: Date.now() });
  return data;
}
